CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    slack_user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE frequency_types (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE reminders (
    id VARCHAR(255) PRIMARY KEY,
    channel_name VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    frequency_type_id INT,
    frequency_value INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (frequency_type_id) REFERENCES frequency_types(id)
);

CREATE TABLE reminder_recipients (
    id VARCHAR(255) PRIMARY KEY,
    reminder_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    is_complete BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (reminder_id) REFERENCES reminders(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE reminder_queue (
    id INT PRIMARY KEY AUTO_INCREMENT,
    reminder_recipient_id VARCHAR(255) NOT NULL,
    send_time TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (reminder_recipient_id) REFERENCES reminder_recipients(id)
);
